# Site
repository: siconge/siconge.github.io
favicon: images/favicon.svg

# Content configuration version
version: 2

# Personal info
name: Sicong E
title: Project Architect
email: esicong@gmail.com
# email_title: Email (Email title override)
phone: +1(000)000-0000
# phone_title: Phone (Phone title override)
website: https://siconge.github.io
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
github_username:  siconge
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: siconge
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Aspiring Data Engineer with a robust background in architecture, specializing in <mark>data pipeline development, <mark>ETL automation, 
  and leveraging advanced analytical tools to drive data-driven decision-making. Proven expertise in <mark>Python</mark>, <mark>SQL</mark>, 
  <mark>AWS</mark>, and <mark>Apache Airflow and Spark</mark>, 
  with a demonstrated ability to manage complex projects and lead cross-functional teams.
  
  Licensed Architect with over a decade of experience, now transitioning to a Data Engineer role to integrate architectural insights with data engineering solutions. 
  Passionate about continuous learning and professional development, aiming to contribute to innovative data engineering projects.
  
  Sicong earned his Master of Architecture from University of Southern California (USC), and Professional Certificate in Data Engineering from MIT xPRO. 
  He is a licensed architect in California and holds AWS Certified Solutions Architect - Associate certification.
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-left
        # border: weak  # Value of `weak` will display a weak border below this item.
                      # Any other value (or no value) means no border will be displayed
        sub_title: Build a Linear Regression Model for Housing Price Prediction
        # link:
        # link_text: Link Text
        additional_links:
          - title:  Github repo for project
            icon: fab fa-github fa-2x
            url: https://github.com/siconge/A-Linear-Regression-Model-for-Housing-Price-Prediction
        # quote: >
        #   Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          **Module 7**
          
          Description about the work on/with the project
          
          **Skills/Tools**: Python SKlearn/Pandas/Numpy
          
          <a href="https://siconge.github.io/A-Linear-Regression-Model-for-Housing-Price-Prediction">Preview</a>
      
      - layout: top-left
        sub_title: ETL Processing and Time Series Analysis of MRTS Dataset
        additional_links:
          - title: Github repo for project
            icon: fab fa-github fa-2x
            url: https://github.com/siconge/ETL-Processing-and-Time-Series-Analysis-of-MRTS-Dataset
        description: | # this will include new lines to allow paragraphs
          **Module 8**
          
          Description about the work on/with the project
          
          **Skills/Tools**: Python SQLAlchemy/Pandas/Numpy, MySQL
          
          <a href="https://siconge.github.io/ETL-Processing-and-Time-Series-Analysis-of-MRTS-Dataset">Preview</a>
      
      - layout: top-left
        sub_title: Creating a Student Grades Database Using Redundant Dictionaries
        additional_links:
          - title: Github repo for project
            icon: fab fa-github fa-2x
            url: https://github.com/siconge/
        description: | # this will include new lines to allow paragraphs
          **Module 15**
          
          Description about the work on/with the project
          
          **Skills/Tools**: Python
          
          <a href="https://siconge.github.io/">Preview</a>
          
      - layout: top-left
        sub_title: Creating a Books Web Application
        additional_links:
          - title: Github repo for project
            icon: fab fa-github fa-2x
            url: https://github.com/siconge/
        description: | # this will include new lines to allow paragraphs
          **Module 15**
          
          Description about the work on/with the project
          
          **Skills/Tools**: Python Flask, HTML
          
          <a href="https://siconge.github.io/">Preview</a>
      
      - layout: top-left
        sub_title: "Real-time Transit Data CDC from MBTA-API to MySQL Database"
        additional_links:
          - title: Github repo for project
            icon: fab fa-github fa-2x
            url: https://github.com/siconge/Realtime-Transit-Data-CDC-from-MBTA-API-to-MySQL-Database
        description: | # this will include new lines to allow paragraphs
          **Module 16**
          
          Description about the work on/with the project
          
          **Skills/Tools**: Python, MySQL, Docker, CLI
          
          <a href="https://siconge.github.io/Realtime-Transit-Data-CDC-from-MBTA-API-to-MySQL-Database">Preview</a>
      
      - layout: top-left
        sub_title: ETL Pipeline Automation and Word Frequencies Visualization
        additional_links:
          - title: Github repo for project
            icon: fab fa-github fa-2x
            url: https://github.com/siconge/ETL-Pipeline-Automation-and-Word-Frequencies-Visualization
        description: | # this will include new lines to allow paragraphs
          **Module 23**
          
          Description about the work on/with the project
          
          **Skills/Tools**: Python, Apache Airflow, JavaScript D3, Docker, HTML
          
          <a href="https://siconge.github.io/ETL-Pipeline-Automation-and-Word-Frequencies-Visualization">Preview</a>

      - layout: top-left
        sub_title: Handling Big Data with Mosquitto, ThingsBoard, and Kafka
        additional_links:
          - title: Github repo for project
            icon: fab fa-github fa-2x
            url: https://github.com/siconge/
        description: | # this will include new lines to allow paragraphs
          **Module 24**
          
          Description about the work on/with the project
          
          **Skills/Tools**: Mosquitto, ThingsBoard, Apache Kafka, Docker, Python
          
          <a href="https://siconge.github.io/">Preview</a>

      - layout: top-left
        sub_title: Machine Learning
        additional_links:
          - title: Github repo for project
            icon: fab fa-github fa-2x
            url: https://github.com/siconge/
        description: | # this will include new lines to allow paragraphs
          **Module 20-21**
          
          Gradient Descent, Classification, Q-Matrix, Deep Neural Network
          
          **Skills/Tools**: Python SKlearn/Pandas/Numpy
          
          <a href="https://siconge.github.io/">Preview</a>


  - title: Experience
    layout: list
    content:
      - layout: top-left
        title: NBBJ
        sub_title: Project Architect
        caption: Sep 2021 - Dec 2023
        link: www.nbbj.com
        # quote: >
        #   Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Description of role
  - title: Education
    layout: list
    content:
      - layout: top-left
        title: MIT xPRO
        sub_title: Prof. Certificate in Data Engineering
        caption: Aug 2023 - Mar 2024
        link: xpro.mit.edu
        # quote: >
          # Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Description of qualification
      - layout: top-left
        title: University of Southern California
        sub_title: Master of Architecture
        caption: Sep 2009 - May 2011
        link: www.usc.edu
        # quote: >
          # Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Description of qualification
  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

      Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# Use this is you are hosting your resume yourself
# theme: jekyll-theme-minimal
# Use this if you are hosting your resume on GitHub
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
